// Generated by CodiumAI

import EpubFile from "./main";

describe("EpubFile", () => {
  // Tests that an error is thrown when the EPUB file has no chapters
  it("should throw an error when EPUB file has no chapters", async () => {
    const epubSettings = {
      title: "Test Book",
      chapters: [],
    };
    const epubFile = new EpubFile(epubSettings);
    await expect(epubFile.constructEpub()).rejects.toThrow(
      "Epub file needs at least one chapter"
    );
  });

  // Tests that an EPUB file with multiple images in a chapter is constructed correctly
  it("should construct EPUB file with multiple images in a chapter", async () => {
    const epubSettings = {
      title: "Test Book",
      chapters: [
        {
          title: "Chapter 1",
          htmlBody: '<img src="image1.jpg"><img src="image2.png">',
        },
      ],
      cover: "cover.jpg",
    };
    const epubFile = new EpubFile(epubSettings);
    const files = await epubFile.constructEpub();
    expect(files.length).toBe(10);
    expect(files[0].path).toBe("EPUB/images/cover.jpg");
    expect(files[1].path).toBe("META-INF/container.xml");
    expect(files[2].path).toBe("EPUB/styles.css");
    expect(files[3].path).toBe("EPUB/script.js");
    expect(files[4].path).toBe("EPUB/images/Chapter_1_image_1.jpg");
    expect(files[5].path).toBe("EPUB/images/Chapter_1_image_2.png");
    expect(files[6].path).toBe("EPUB/content/Chapter_1.xhtml");
    expect(files[7].path).toBe("EPUB/Test_Book.opf");
    expect(files[8].path).toBe("EPUB/toc.xhtml");
    expect(files[9].path).toBe("EPUB/toc.ncx");
  });

  // Tests that an error is thrown when the EPUB file has no title
  it("should throw an error when the EPUB file has no title", async () => {
    const epubSettings = {
      title: "",
      chapters: [
        {
          fileName: "chapter1.xhtml",
          title: "Chapter 1",
          htmlBody: "<p>Chapter 1 content</p>",
        },
      ],
    };
    const epubFile = new EpubFile(epubSettings);
    await expect(epubFile.constructEpub()).rejects.toThrow(
      "Epub file needs a title"
    );
  });

  // Tests that an EPUB file with no author is handled correctly
  it("should throw an error when no author is provided", async () => {
    const epubSettings = {
      title: "Test Book",
      chapters: [
        {
          title: "Chapter 1",
          htmlBody: "<p>Chapter 1</p>",
        },
      ],
    };
    const epubFile = new EpubFile(epubSettings);
    const files = await epubFile.constructEpub();
    expect(files[4].content).toContain("<dc:creator>Unnamed</dc:creator>");
  });

  // Tests that the constructEpub method sets a book ID if none is provided in the EpubSettings object
  it("should set a book ID if none is provided", async () => {
    const epubSettings = {
      title: "Test Book",
      chapters: [
        {
          title: "Chapter 1",
          htmlBody: "<p>Chapter 1</p>",
        },
      ],
    };
    const epubFile = new EpubFile(epubSettings);
    const files = await epubFile.constructEpub();
    const opfFile = files.find((file) => file.path.endsWith(".opf"));
    const opfContent = opfFile?.content;
    expect(opfContent).toMatch(/.*id=\"BookId\">\d+<.*/);
  });

  // Tests that the EPUB file is constructed correctly when the js parameter is empty
  it("should construct EPUB file with empty js", async () => {
    const epubSettings = {
      title: "Test Book",
      chapters: [
        {
          title: "Chapter 1",
          htmlBody: "<h1>Chapter 1</h1>",
        },
      ],
      js: "",
    };
    const epubFile = new EpubFile(epubSettings);
    const files = await epubFile.constructEpub();
    expect(files.length).toBe(7);
    expect(files[0].path).toBe("META-INF/container.xml");
    expect(files[1].path).toBe("EPUB/styles.css");
    expect(files[2].path).toBe("EPUB/script.js");
    expect(files[3].path).toBe("EPUB/content/Chapter_1.xhtml");
    expect(files[4].path).toBe("EPUB/Test_Book.opf");
    expect(files[5].path).toBe("EPUB/toc.xhtml");
    expect(files[6].path).toBe("EPUB/toc.ncx");
  });
});

